# Generated by Django 5.1.5 on 2025-01-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
